<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="Akka.TestKit.Xunit" />
    <PackageReference Include="SwiftBets.BuildingBlocks.Testing" />
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
    <ProjectReference Include="../../src/SwiftBets.Risk.Infrastructure/SwiftBets.Risk.Infrastructure.csproj" />
    <ProjectReference Include="../../src/SwiftBets.Risk.Migrator/SwiftBets.Risk.Migrator.csproj" Aliases="migrator" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Shouldly" />
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
